Allow numeric values for GreaterThan and LessThan
bjd-php/parsley-bundle pull request #19
Opened 2020-10-13 15:43 UTC by Matts

Closes #18 

Kindly add label `hacktoberfest-accepted` to this PR

2020-10-14 12:16 UTC, J-Ben87 requested changes
Hi Matts,

Thank you for submitting the PR. I only have a few improvements to suggest, otherwise that looks good to me :slightly_smiling_face:

2020-10-14 12:16 UTC, J-Ben87 commented on Constraint/Constraints/GreaterThan.php
> +            ->setAllowedTypes('value', ['numeric', 'string'])
You shouldn't allow `string` type here: `numeric` type already handles values like `"5"` or `"5.2"`.

By allowing `string` type, values like `"foo"` would be accepted, which is not supported by Parsley.

2020-10-14 12:16 UTC, J-Ben87 commented on Constraint/Constraints/LessThan.php
> +            ->setAllowedTypes('value', ['numeric', 'string'])
Same as above.

2020-10-14 12:16 UTC, J-Ben87 commented on Tests/Constraint/Constraints/GreaterThanOrEqualTest.php
> +            'value' => [],
You could assert that `'value' => 'foo',` throws the exception

2020-10-14 12:16 UTC, J-Ben87 commented on Tests/Constraint/Constraints/GreaterThanTest.php
> +            'value' => [],
Same as above.

2020-10-14 12:16 UTC, J-Ben87 commented on Tests/Constraint/Constraints/LessThanOrEqualTest.php
> +            'value' => [],
Same as above.

2020-10-14 12:16 UTC, J-Ben87 commented on Tests/Constraint/Constraints/LessThanTest.php
> +            'value' => [],
Same as above.

2020-10-15 18:00 UTC, Matts commented
> Hi Matts,
> 
> Thank you for submitting the PR. I only have a few improvements to suggest, otherwise that looks good to me 🙂

Fixed.

2020-10-15 18:42 UTC, J-Ben87 approved these changes

2020-10-15 18:44 UTC, merged

2020-10-15 18:48 UTC, J-Ben87 commented
Thank you for contributing :slightly_smiling_face: 
Your contribution will be available as version 2.1.2 in Packagist.